### PR TITLE
i2c: OpenTitan driver fixes

### LINKED ISSUE #680: opentitan i2c: zero-length requests hang
This is somewhat related to #672, but not exactly.

The [micropython `machine_i2c_scan`](https://github.com/micropython/micropython/blob/647c8b96cae7e202c7a020395b7cfe65e5b8ce04/extmod/machine_i2c.c#L322-L338) command performs zero-length writes with a STOP condition.

```c
static mp_obj_t machine_i2c_scan(mp_obj_t self_in) {
    mp_obj_base_t *self = MP_OBJ_TO_PTR(self_in);
    mp_obj_t list = mp_obj_new_list(0, NULL);
    // 7-bit addresses 0b0000xxx and 0b1111xxx are reserved
    for (int addr = 0x08; addr < 0x78; ++addr) {
        int ret = mp_machine_i2c_writeto(self, addr, NULL, 0, true);
        if (ret == 0) {
            mp_obj_list_append(list, MP_OBJ_NEW_SMALL_INT(addr));
        }
        // This scan loop may run for some time, so process any pending events/exceptions,
        // or allow the port to run any necessary background tasks.  But do it as fast as
        // possible, in particular we are not waiting on any events.
        mp_event_handle_nowait();
    }
    return list;
}
MP_DEFINE_CONST_FUN_OBJ_1(machine_i2c_scan_obj, machine_i2c_scan);
```

In the case of the Opentitan i2c driver, this results in it hanging.

We should:

1. Fix this
2. Add sDDF tests to verify this case is OK

### PR DESCRIPTION
**Pull request by midnightveil**
~~Also adds an ina219 example? I'm unsure if this is worth keeping.~~ Pulled out in #689.

Thanks to @Liamolucko and @omeh-a.

Fixes #680

### CODE REVIEW

File: drivers/i2c/opentitan/cheshire-i2c.h [hunk 1]
```diff
@@ -69,7 +69,6 @@ typedef struct opentitan_i2c_regs {
 
 /* HW properties */
 #define OPENTITAN_I2C_FIFO_DEPTH    (64)
-#define OPENTITAN_I2C_READ_MAX      (64)
```
Comment (omeh-a) [inline drivers/i2c/opentitan/cheshire-i2c.h:72]: Is there a reason to remove this? We limited this to 64 previously because it means that it is an invariant that one entry into S_CMD causes exactly one entry to S_CMD_RET. The state machine isn't designed to handle this, and in previous discussions with Liam we agreed that it was probably better to keep this here for reliability.

Comment (midnightveil) [reply drivers/i2c/opentitan/cheshire-i2c.h:72]: This was Liam and you, not me.

@Liamolucko.

Comment (Liamolucko) [reply drivers/i2c/opentitan/cheshire-i2c.h:72]: The limit of 64 bytes per `S_CMD` is still enforced (well, newly enforced), I just personally found it clearer to use `OPENTITAN_I2C_FIFO_DEPTH` directly to indicate that that's where the limit is coming from.

Comment (omeh-a) [reply drivers/i2c/opentitan/cheshire-i2c.h:72]: Ah I see. All good then :)

**Review by omeh-a — APPROVED** [review]
